### PR TITLE
Bring back 03b538f (multi-factor authentication support)

### PR DESCRIPTION
**Pull request by abompard**
It looks like commit 03b538f was lost in the recent refactor. This PR is a rebase.

### CODE REVIEW

**Comment by FirefighterBlu3** [comment]
Hi @abompard - please make this pull request against the develop branch

**Comment by abompard** [comment]
Done!

**Comment by spaceone** [comment]
A test case would be good - as from the code this is not easily understandable.

**Comment by FirefighterBlu3** [comment]
@spaceone done

**Pull request merged**
